/**
 * Environment Constants
 * Environment-specific configuration and feature flags
 */

export const ENV = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  IS_DEVELOPMENT: process.env.NODE_ENV === 'development',
  IS_PRODUCTION: process.env.NODE_ENV === 'production',
  IS_TEST: process.env.NODE_ENV === 'test',
} as const;

export const FEATURE_FLAGS = {
  // Development Features
  ENABLE_DEBUG_MODE: ENV.IS_DEVELOPMENT,
  ENABLE_MOCK_AUTH: ENV.IS_DEVELOPMENT,
  ENABLE_ANALYTICS: !ENV.IS_DEVELOPMENT,
  ENABLE_ERROR_REPORTING: ENV.IS_PRODUCTION,
  
  // Core Features
  ENABLE_SEARCH: true,
  ENABLE_CHAT: true,
  ENABLE_DOCUMENTS: true,
  ENABLE_INTEGRATIONS: true,
  ENABLE_ANALYTICS_TRACKING: true,
  ENABLE_NOTIFICATIONS: true,
  
  // Advanced Features
  ENABLE_REAL_TIME_SEARCH: true,
  ENABLE_DOCUMENT_PREVIEW: true,
  ENABLE_BULK_OPERATIONS: true,
  ENABLE_API_RATE_LIMITING: ENV.IS_PRODUCTION,
  ENABLE_CACHING: true,
  ENABLE_OFFLINE_MODE: false,
  
  // UI Features
  ENABLE_DARK_MODE: true,
  ENABLE_THEME_CUSTOMIZATION: true,
  ENABLE_INTERNATIONALIZATION: true,
  ENABLE_ONBOARDING: true,
  ENABLE_TOOLTIPS: true,
  ENABLE_ANIMATIONS: true,
  
  // Security Features
  ENABLE_CSRF_PROTECTION: ENV.IS_PRODUCTION,
  ENABLE_CONTENT_SECURITY_POLICY: ENV.IS_PRODUCTION,
  ENABLE_RATE_LIMITING: ENV.IS_PRODUCTION,
  ENABLE_SESSION_TIMEOUT: true,
} as const;

export const API_CONFIG = {
  BASE_URL: ENV.IS_PRODUCTION 
    ? 'https://api.ragsuite.com' 
    : 'http://localhost:5000',
  TIMEOUT: ENV.IS_PRODUCTION ? 30000 : 10000,
  RETRY_ATTEMPTS: ENV.IS_PRODUCTION ? 3 : 1,
  RETRY_DELAY: 1000,
  ENABLE_CACHING: FEATURE_FLAGS.ENABLE_CACHING,
  ENABLE_RATE_LIMITING: FEATURE_FLAGS.ENABLE_API_RATE_LIMITING,
} as const;

export const STORAGE_CONFIG = {
  ENABLE_PERSISTENCE: true,
  ENABLE_ENCRYPTION: ENV.IS_PRODUCTION,
  DEFAULT_TTL: 24 * 60 * 60 * 1000, // 24 hours
  MAX_SIZE: ENV.IS_PRODUCTION ? 1000 : 100,
} as const;

export const ANALYTICS_CONFIG = {
  ENABLED: FEATURE_FLAGS.ENABLE_ANALYTICS_TRACKING,
  ENDPOINT: ENV.IS_PRODUCTION 
    ? 'https://analytics.ragsuite.com/track' 
    : 'http://localhost:5000/api/analytics',
  DEBUG: ENV.IS_DEVELOPMENT,
  BATCH_SIZE: 10,
  FLUSH_INTERVAL: 5000,
} as const;

export const ERROR_REPORTING_CONFIG = {
  ENABLED: FEATURE_FLAGS.ENABLE_ERROR_REPORTING,
  ENDPOINT: ENV.IS_PRODUCTION 
    ? 'https://errors.ragsuite.com/report' 
    : 'http://localhost:5000/api/errors',
  DEBUG: ENV.IS_DEVELOPMENT,
  INCLUDE_STACK_TRACE: ENV.IS_DEVELOPMENT,
  INCLUDE_USER_AGENT: true,
  INCLUDE_URL: true,
} as const;

export const NOTIFICATION_CONFIG = {
  ENABLED: FEATURE_FLAGS.ENABLE_NOTIFICATIONS,
  MAX_NOTIFICATIONS: 5,
  DEFAULT_DURATION: 5000,
  ENABLE_SOUNDS: true,
  ENABLE_BROWSER_NOTIFICATIONS: ENV.IS_PRODUCTION,
} as const;

export const CACHE_CONFIG = {
  ENABLED: FEATURE_FLAGS.ENABLE_CACHING,
  MAX_SIZE: ENV.IS_PRODUCTION ? 1000 : 100,
  DEFAULT_TTL: 5 * 60 * 1000, // 5 minutes
  ENABLE_PERSISTENCE: true,
} as const;

export const SECURITY_CONFIG = {
  ENABLE_CSRF_PROTECTION: FEATURE_FLAGS.ENABLE_CSRF_PROTECTION,
  ENABLE_CSP: FEATURE_FLAGS.ENABLE_CONTENT_SECURITY_POLICY,
  SESSION_TIMEOUT: 24 * 60 * 60 * 1000, // 24 hours
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION: 15 * 60 * 1000, // 15 minutes
} as const;

export const DEVELOPMENT_CONFIG = {
  ENABLE_HOT_RELOAD: ENV.IS_DEVELOPMENT,
  ENABLE_DEBUG_PANEL: ENV.IS_DEVELOPMENT,
  ENABLE_PERFORMANCE_MONITORING: ENV.IS_DEVELOPMENT,
  ENABLE_MOCK_DATA: ENV.IS_DEVELOPMENT,
  ENABLE_CONSOLE_LOGGING: ENV.IS_DEVELOPMENT,
} as const;

export const PRODUCTION_CONFIG = {
  ENABLE_COMPRESSION: ENV.IS_PRODUCTION,
  ENABLE_MINIFICATION: ENV.IS_PRODUCTION,
  ENABLE_TREE_SHAKING: ENV.IS_PRODUCTION,
  ENABLE_SOURCE_MAPS: false,
  ENABLE_CONSOLES: false,
} as const;
